function absorption = importfile(DIR, dataLines)
%IMPORTFILE Import data from a text file
%  TYR118M3 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  TYR118M3 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  tyr118m3 = importfile("C:\Users\student\Desktop\ismail\Absorptionsmessungen\Tyrosine");
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Nov-2020 11:18:04

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [20, Inf];
end
%%

if(~isempty(DIR)) % Wenn DIR gegeben ist. (~ = NICHT) (isempty = ist leer?)
    cd(DIR); % �ndere den Pfad zu "DIR" (cd = Change Directory)
end

%% Alle Dateien suchen, die mit ".txt" beschriftet sind
A = dir(strcat('*','.txt')); % (strcat = kombiniere Strings)
                             % Erstelle ein Directory mit den .txt Dateien



%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["TITLE", "Tyrosin"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["TITLE", "Tyrosin"], "DecimalSeparator", ",");
opts = setvaropts(opts, ["TITLE", "Tyrosin"], "ThousandsSeparator", ".");

for k=1:length(A)
% Import the data
    filename = A(k).name;
    M = readtable(filename, opts);

    %% Convert to output type
    M = table2array(M);

    for a=1:length(M)
        if isnan(M(a))
            a = a-1;
            break
        end
    end
    absorption(:,:,k) = M(1:a,:);
end
end



