function struct = importFluorometer(DIR, dataLines)
%IMPORTFILE1 Import data from a text file
%  TYR106M2 = IMPORTFILE1(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  TYR106M2 = IMPORTFILE1(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  tyr106m2 = importfile1("C:\Users\student\Desktop\ismail\Messungen_zhu jinhan\tyrosine\tyr106m_2.csv", [23, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-Nov-2020 10:52:12

%% Input handling
load woerterbuch.mat

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, 6]; %23
end


%%

if(~isempty(DIR)) % Wenn DIR gegeben ist. (~ = NICHT) (isempty = ist leer?)
    cd(DIR); % Andere den Pfad zu "DIR" (cd = Change Directory)
end


%% Alle Dateien suchen, die mit ".txt" beschriftet sind
A = dir(strcat('*','.csv')); % (strcat = kombiniere Strings)
                             % Erstelle ein Directory mit den .xls Dateien

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Wellenlngenm", "IntensittAU", "IntensittDunkelkorrigiertAU"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Wellenlngenm", "TrimNonNumeric", true);
opts = setvaropts(opts, "Wellenlngenm", "ThousandsSeparator", ",");

% Import the data


for k=1:length(A)
% Import the data
    opts.DataLines = [3,6];
    filename = A(k).name;
    
    stoffNameAbkruzung = filename(1:3);
    stoffName = ...
        woerterbuch.stoffName(find(woerterbuch.stoffNameAbkurzung...
        == stoffNameAbkruzung));
    stoffKonzentration = str2double(filename(4:6));
    einheitsPraefix = filename(7);
    einheit = ...
        woerterbuch.einheit(find(woerterbuch.einheitsPraefix ...
        == einheitsPraefix));
    
    konzentration = stoffKonzentration * einheit;
    
    temp = readtable(filename, opts);
    temp = table2array(temp(:,1));
    logical = (find(temp~=0));
    excitation = temp(logical);    
    
    opts.DataLines = [23,inf];
    M = readtable(filename, opts);
%% Convert to output type
    M = table2array(M);
     for a=1:length(M)
            if isnan(M(a))
                a = a-1;
                break
            end
     end
     %fluorescence(:,:,k) = M(1:a,:);

struct(k).name=stoffName;
struct(k).konzentration=konzentration;
struct(k).excitation = excitation;
struct(k).wellenlaenge = M(1:a,1);
struct(k).ohneKorrektur = M(1:a,2);
struct(k).mitKorrektur = M(1:a,3);
end

end







